//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace TestCaseAndProblem {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(6)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ProblemSheet : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button buttonEditProblem;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBoxProblemType;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBoxProblemLevel;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBoxReportor;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ProblemSheet(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet4", "Sheet4") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.ProblemSheet = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.buttonEditProblem = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1E67C1FB51E78F146D51A3581BCADDD83395F1", "1E67C1FB51E78F146D51A3581BCADDD83395F1", this, "buttonEditProblem");
            this.comboBoxProblemType = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "398D73238385FF34A523970039398042302463", "398D73238385FF34A523970039398042302463", this, "comboBoxProblemType");
            this.comboBoxProblemLevel = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "4FFBCC08E4D4BD44C2F4807A460275CCAE6854", "4FFBCC08E4D4BD44C2F4807A460275CCAE6854", this, "comboBoxProblemLevel");
            this.comboBoxReportor = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "53D39B09B543F9546115A036505E343DAEB3B5", "53D39B09B543F9546115A036505E343DAEB3B5", this, "comboBoxReportor");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // buttonEditProblem
            // 
            this.buttonEditProblem.BackColor = System.Drawing.Color.DodgerBlue;
            this.buttonEditProblem.ForeColor = System.Drawing.Color.Snow;
            this.buttonEditProblem.Name = "buttonEditProblem";
            this.buttonEditProblem.Text = "编辑问题";
            this.buttonEditProblem.UseVisualStyleBackColor = false;
            this.buttonEditProblem.Visible = false;
            // 
            // comboBoxProblemType
            // 
            this.comboBoxProblemType.BackColor = System.Drawing.Color.DodgerBlue;
            this.comboBoxProblemType.ForeColor = System.Drawing.Color.Snow;
            this.comboBoxProblemType.Items.AddRange(new object[] {
                        "文档",
                        "程序",
                        "设计",
                        "其它"});
            this.comboBoxProblemType.Name = "comboBoxProblemType";
            this.comboBoxProblemType.Text = "类型";
            this.comboBoxProblemType.Visible = false;
            // 
            // comboBoxProblemLevel
            // 
            this.comboBoxProblemLevel.BackColor = System.Drawing.Color.DodgerBlue;
            this.comboBoxProblemLevel.ForeColor = System.Drawing.Color.Snow;
            this.comboBoxProblemLevel.Items.AddRange(new object[] {
                        "致命",
                        "严重",
                        "一般",
                        "轻微"});
            this.comboBoxProblemLevel.Name = "comboBoxProblemLevel";
            this.comboBoxProblemLevel.Text = "级别";
            this.comboBoxProblemLevel.Visible = false;
            // 
            // comboBoxReportor
            // 
            this.comboBoxReportor.BackColor = System.Drawing.Color.DodgerBlue;
            this.comboBoxReportor.ForeColor = System.Drawing.Color.Snow;
            this.comboBoxReportor.Name = "comboBoxReportor";
            this.comboBoxReportor.Text = "报告人";
            this.comboBoxReportor.Visible = false;
            // 
            // ProblemSheet
            // 
            this.buttonEditProblem.BindingContext = this.BindingContext;
            this.comboBoxProblemType.BindingContext = this.BindingContext;
            this.comboBoxProblemLevel.BindingContext = this.BindingContext;
            this.comboBoxReportor.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static ProblemSheet _ProblemSheet;
        
        internal static ProblemSheet ProblemSheet {
            get {
                return _ProblemSheet;
            }
            set {
                if ((_ProblemSheet == null)) {
                    _ProblemSheet = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
